name: Maven CI/CD for Assignment 2

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean compile --file pom.xml

      - name: Run unit tests
        run: mvn -B test --file pom.xml

      - name: Package JAR
        run: mvn -B package --file pom.xml

      - name: Run CLI benchmarks (small n for CI)
        run: |
          mkdir -p performance-plots
          echo "n,type,algorithm,time_ms,comparisons,swaps,array_accesses,memory_allocations,memory_used_kb,is_correct" > performance-plots/ci_benchmarks.csv
          sizes=(100 1000)
          types=(random sorted reverse nearly)
          for size in "${sizes[@]}"; do
            for type in "${types[@]}"; do
              mvn exec:java -Dexec.mainClass="org.example.cli.BenchmarkRunner" -Dexec.args="$size $type selection" >> performance-plots/ci_benchmarks.csv
            done
          done

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks-and-plots
          path: performance-plots/ci_benchmarks.csv

      - name: Run JMH benchmarks (optional, small n)
        if: false
        run: mvn package 
          java -jar target/jmh-benchmarks.jar -f 1 -wi 2 -i 2 -rff performance-plots/ci_jmh.csv -rf csv org.example.algoritms.JMHSelectionSortBenchmark